name: 删除历史运行日志
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
# Run monthly, at 00:00 on the 1st day of month.

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete_workflow_runs
        uses: smallprogram/delete-workflow-runs@main
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 6
