name: 超级直播间红包雨

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12,13,14,15 19 1 *'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: shylocks/Loon
          ref: 'main'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          curl https://raw.githubusercontent.com/LXK9301/jd_scripts/master/package.json -o package.json
          curl https://raw.githubusercontent.com/x1iu/scripts_jd/master/USER_AGENTS.js -o USER_AGENTS.js
          curl https://raw.githubusercontent.com/x1iu/jd_scripts/master/jdCookie.js -o jdCookie.js
          npm install
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: '运行领京豆'
        run: |
          curl https://raw.githubusercontent.com/x1iu/jd_scripts/master/accwait.py -o wait.py
          python3 wait.py 0.1 0.1 29
          curl https://raw.githubusercontent.com/shylocks/Loon/main/jd_live_redrain.js -o jd_redrain.js
          node jd_redrain.js
          curl https://raw.githubusercontent.com/shylocks/Loon/main/jd_live_redrain.js -o jd_redrain.js
          node jd_redrain.js
          curl https://raw.githubusercontent.com/shylocks/Loon/main/jd_live_redrain.js -o jd_redrain.js
          node jd_redrain.js
          sleep 1m
          curl https://raw.githubusercontent.com/shylocks/Loon/main/jd_live_redrain.js -o jd_redrain.js
          node jd_redrain.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}