# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: htt1ps://help.github.com/actio ns/language-and-framework-guides/using-nodejs-with-github-actions

name: 京喜工厂开团

on:
  workflow_dispatch:
  schedule:
    - cron: '57,10,25,40 15,16,17,18,23,3,5,11,13 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_updateFactoryTuanID
jobs:
  build:
    env:
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【京喜工厂开团'
        run: |
          node jd_jxFactoryCreateTuan.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
      - name: commit
        run: |
          git config --global user.email 2705322732@qq.com
          git config --global user.name hajiuhajiu
          git add .
          git commit -m "update byGithub Action" -a || echo "Nothing to update"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: master

      
